# Generated by Django 6.0.3 on 2026-04-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
