# Generated by Django 6.0.3 on 2026-04-04 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('view_dashboard_summary', 'Can view dashboard summary'), ('view_dashboard_trends', 'Can view dashboard trends'), ('export_financialrecord', 'Can export financial records'), ('manage_own_financialrecord', 'Can manage own financial records only'), ('view_all_financialrecords', 'Can view financial records of all users'), ('approve_financialrecord', 'Can approve/reject financial records')], 'verbose_name': 'Financial Record', 'verbose_name_plural': 'Financial Records'},
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['user', 'date'], name='finance_fin_user_id_e9b48d_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['is_deleted'], name='finance_fin_is_dele_c8cf73_idx'),
        ),
    ]
